chunk_size: 29
mp3_file: C:/Users/freyd/Desktop/HunSpeechRecognition/PROBA/audio.mp3
mp3_duration: 7301.4675625
noise_treshold: -60
silence_dur: 0.5
project_folder: C:/Users/freyd/Desktop/HunSpeechRecognition/PROBA
