cuda_path: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.3
cuda_bin_path: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.3/bin
cuda_libnvvp_path: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.3/libnvvp
physx_path: C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common
nvdlisr_path: C:/Program Files/NVIDIA Corporation/NVIDIA NvDLISR
cudnn_bin_path: '[INSTALL_DIR]/cudnn-windows-x86_64-8.9.6.50_cuda12-archive/bin'
cudnn_bin_path2: '[INSTALL_DIR]/_internal/torch/lib'
ffmpeg_path: '[INSTALL_DIR]/deploy/ffmpeg-master-latest-win64-gpl/bin'
ffmpeg_path2: '[INSTALL_DIR]/ffmpeg-master-latest-win64-gpl/bin'
last_project_dir: C:/Users/freyd/Desktop/HunSpeechRecognition/testing/NEW/PROBA
last_project_name: PROBA
last_project_audio: C:/Users/freyd/Desktop/HunSpeechRecognition/testing/NEW/PROBA/proba.wav
